apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-demo-keyvault
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: spring-boot-demo
        app: spring-boot-demo
        aadpodidbinding: demo
    spec:
      containers:
      - name: spring-boot-container
        imagePullPolicy: Always
        image: testmsi.azurecr.io/azure-keyvault-secrets-spring-boot:example
        env:
          - name: KEYVAULT_URI
            value: "https://testmsi.vault.azure.net"
        ports:
          - containerPort: 80
            name: http
            protocol: TCP